language: python

branches:
  except:
  - dev
  - extended_datafiles


matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7

install:
- pip install cython
- pip install .
# command to run tests

