language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
        - os: linux
          sudo: required
          python: 3.8
        - os: windows
          python: 3.8

install:
- pip install cython
- pip install Sphinx>=1.4.3
- pip install .

script: (cd docs ; make doctest)
